### PR TITLE
Google signin

### PR DESCRIPTION
**Pull request by karmelyoei**

### CODE REVIEW

**Review by yaqootturman — COMMENTED** [review]
+ the folder components should be Components
+ document the code, Please!
+ change the name of PR
and + no need to push empty files, we can add them later!

**Comment by mantagen** [comment]
@karmelyoei could you write the steps for how to test the functionality of this PR? I have started the app but I don;t know how to test it?

**Comment by karmelyoei** [comment]
> @karmelyoei could you write the steps for how to test the functionality of this PR? I have started the app but I don;t know how to test it?

For this PR :
pull the pull request locally then all you have to do is 

1. cd client 

1. npm i

1. create a .env file I will give you the private keys till we make Heroku deploy for our project

1. cd .. && npm i

1. Run ( npm run dev)

**Comment by karmelyoei** [comment]
> @karmelyoei could you write the steps for how to test the functionality of this PR? I have started the app but I don't know how to test it?

You will see on the home page 

googleSignin


after you sign in successfully it will direct you to a new page with /dashboard endpoint displaying your name with a sign-out 

googledashboard


when you click the signout it will remove your info sign in and direct you to the home page

**Review by mantagen — APPROVED** [review]

**Review by yaqootturman — APPROVED** [review]

**Pull request merged**
