### PR TITLE
Adds a pull request template

### LINKED ISSUE #30: PR and Issue description.
Hey guys, make sure you add adequate description text to your future PRs and issues.

### LINKED ISSUE #39: Create a pull request template
https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

Having a "pull request template" means that all pull requests have a clear description, and it will be easy for reviewers to test+review.

### PR DESCRIPTION
**Pull request by mantagen**
### What does this PR do?
- Create `pull_request_template.md` so that all pull request descriptions look similar. Each pull request will start with these hints:
  - "What does this PR do?"
    - this is a description of the changes you've made
  - "Does this Fix an Issue?"
    - if this PR should automatically close an issue, you can write "Fixes #__" then when the PR is merged, the issue will close. If it is related to an issue but _shouldn't_ close it automatically, you can write "Related #__"
  - "How to test this PR"
    - here you should write the steps for the review to test the issue. Eg:
      - run app
      - navigate to home page
      - click on "sign in" button
      - you should be able to sign in without an error
    - if the changes are only back end, then you can skip this section, or just say "run `npm test`"
  - "Screenshots of changes"
    - if you make changes to the front end, you should include screenshots here so that the review can see what it _should_ look like

### Does this Fix an Issue?
Fixes #39
Fixes #30

### CODE REVIEW

**Review by yaqootturman — APPROVED** [review]
Great, I totally agree with your template!

**Review by karmelyoei — APPROVED** [review]
That's a lot to do according to the time-limited 
it will require more time to write the issue and PR documentation with md fille 
well I will try to do it 
my mainly concerns are only to write a clean efficient code

**Comment by hshahwan** [comment]
@karmelyoei I don't think so Karmel, it will not take a lot of time.
that will help you to be more organized and  that will help another to review your PR.

**Review by rubasider — APPROVED** [review]

**Comment by mantagen** [comment]
> my mainly concerns are only to write a clean efficient code

@karmelyoei i completely agree with you! Soon it will be _very quick_ to write PR descriptions, and it will mean that the reviewer can help you write clean efficient code, because they don't have to waste a lot of time to understand what the PR is for.

**Pull request merged**
